### ISSUE TITLE
Create 1.0 release

### ISSUE THREAD

**Issue by TomHAnderson** [gianarb/angry#3]
Create a 1.0 angry release

**Comment by TomHAnderson** [comment]
https://github.com/gianarb/angry/releases shows no releases.  

composer shows:

``` sh
Problem 1
    - The requested package gianarb/angry ^1.0 exists as gianarb/angry[dev-gianarb-patch-1, dev-gianarb-patch-2, dev-master] but these are rejected by your constraint.
```

The 1.0 release was not created.

**Comment by gianarb** [comment]
nop :D

**Comment by TomHAnderson** [comment]
Without a release I'm prone to write my own library to do the same thing.  angry solved the problem first.  Are you going to require this package as dev-master only?

**Comment by gianarb** [comment]
No no i have in Plan a release i think tomorrow
